# Replace this with a more specific image, like python:3.8
FROM ubuntu:18.04

WORKDIR /app

# Replace this with more selective COPY commands of only needed files
COPY ./* /

RUN echo "Hello from Dockerfile"
