STAGE ?= 'local'

clean:
	@echo 'This would clean $(STAGE), but must first be implemented'
	exit 1

build:
	@echo 'This would build $(STAGE), but must first be implemented'
	exit 1

deploy:
	@echo 'This would deploy $(STAGE), but must first be implemented'
	exit 1

test: unit-test system-test
	@echo 'Tested $(STAGE)'

unit-test:
	@echo 'Unit tests not implemented yet'
	exit 1

system-test:
	@echo 'System tests not implemented yet'
	exit 1

coverage:
	@echo 'Tests not implemented yet, cannot compute coverage'
	exit 1

lint:
	@echo 'Linting not implemented yet'
	exit 1
